import FAQTopSection from '@/components/faq/FAQTopSection'
import Head from 'next/head'


export default function FAQ() {
  return (
    <>
        <Head>
            <title>IBS Consulting | FAQ</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <FAQTopSection />
    </>
  )
}