import Banner from '@/components/home/Banner'
import CounterSection from '@/components/home/CounterSection'
import HeroSection from '@/components/home/HeroSection'
import IntroSection from '@/components/home/IntroSection'
import Testimonial from '@/components/home/Testimonial'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>IBS Consulting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <IntroSection />
      {/* <Banner /> */}
      <CounterSection />
      <Testimonial />
    </>
  )
}
