import SuccessTopSection from '@/components/success/SuccessTopSection'
import Head from 'next/head'


export default function Success() {
  return (
    <>
      <Head>
        <title>IBS Consulting | Success Stories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SuccessTopSection />

    </>
  )
}